# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: file-contents-sorter
      - id: forbid-new-submodules
      - id: mixed-line-ending
      - id: name-tests-test
      - id: no-commit-to-branch
      - id: pretty-format-json
      - id: requirements-txt-fixer
      - id: sort-simple-yaml
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 21.5b1
    hooks:
      - id: black
        args:
          - --config=lang/py/pyproject.toml

  - repo: https://github.com/PyCQA/isort
    rev: 5.8.0
    hooks:
      - id: isort
        args:
          - --profile=black

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.19.0
    hooks:
      - id: pyupgrade

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.5
    hooks:
      - id: rubocop
      - id: shellcheck
      - id: shfmt

  - repo: https://github.com/ejba/pre-commit-maven
    rev: v0.3.0
    hooks:
      - id: maven-spotless-apply

  - repo: https://github.com/pre-commit/mirrors-fixmyjs
    rev: v2.0.0
    hooks:
    - id: fixmyjs
